import { Dataset, RevenueData, PaymentHistory } from './types';

export const MOCK_DATASETS: Dataset[] = [
  {
    id: '1',
    title: 'High-Quality Medical Imaging (MRI)',
    description: 'A curated dataset of 5,000+ anonymized MRI scans for neurological research and AI training.',
    type: 'image',
    price: 450,
    license: 'Commercial Use',
    rating: 4.8,
    downloads: 124,
    revenue: 55800,
    creator: 'NeuroScan Labs',
    createdAt: '2024-01-15',
    sampleData: ['mri_scan_001.jpg', 'mri_scan_002.jpg', 'mri_scan_003.jpg'],
    tags: ['Healthcare', 'Radiology', 'MRI'],
    isVerified: true,
  },
  {
    id: '2',
    title: 'Multi-Language Customer Support Dialogues',
    description: 'Over 100,000 transcribed and labeled customer support interactions in 12 languages.',
    type: 'text',
    price: 120,
    license: 'Research Only',
    rating: 4.5,
    downloads: 450,
    revenue: 54000,
    creator: 'GlobalText AI',
    createdAt: '2024-02-10',
    sampleData: ['dialogue_en_01.txt', 'dialogue_es_01.txt'],
    tags: ['NLP', 'Multilingual', 'Customer Service'],
    isVerified: true,
  },
  {
    id: '3',
    title: 'Python Security Vulnerability Snippets',
    description: 'A dataset of 10,000+ Python code snippets with labeled security vulnerabilities (OWASP Top 10).',
    type: 'code',
    price: 299,
    license: 'Commercial Use',
    rating: 4.9,
    downloads: 89,
    revenue: 26611,
    creator: 'SecureCode Systems',
    createdAt: '2024-03-05',
    sampleData: ['vuln_snippet_01.py', 'vuln_snippet_02.py'],
    tags: ['Cybersecurity', 'Python', 'Static Analysis'],
    isVerified: true,
  },
  {
    id: '4',
    title: 'Urban Traffic Surveillance Video',
    description: '4K video footage from 50 different urban intersections for autonomous driving training.',
    type: 'image',
    price: 800,
    license: 'Commercial Use',
    rating: 4.2,
    downloads: 45,
    revenue: 36000,
    creator: 'CityVision AI',
    createdAt: '2024-03-20',
    sampleData: ['traffic_cam_01.mp4', 'traffic_cam_02.mp4'],
    tags: ['Autonomous Driving', 'Computer Vision', 'Urban'],
    isVerified: false,
  },
];

export const REVENUE_STATS: RevenueData[] = [
  { month: 'Oct', revenue: 12000, downloads: 150 },
  { month: 'Nov', revenue: 15000, downloads: 180 },
  { month: 'Dec', revenue: 18000, downloads: 210 },
  { month: 'Jan', revenue: 22000, downloads: 250 },
  { month: 'Feb', revenue: 19000, downloads: 220 },
  { month: 'Mar', revenue: 25000, downloads: 300 },
];

export const PAYMENT_HISTORY: PaymentHistory[] = [
  { id: 'TX-9012', date: '2024-03-28', amount: 450, status: 'completed', datasetName: 'High-Quality Medical Imaging (MRI)' },
  { id: 'TX-9011', date: '2024-03-25', amount: 120, status: 'completed', datasetName: 'Multi-Language Customer Support Dialogues' },
  { id: 'TX-9010', date: '2024-03-20', amount: 299, status: 'completed', datasetName: 'Python Security Vulnerability Snippets' },
  { id: 'TX-9009', date: '2024-03-15', amount: 450, status: 'pending', datasetName: 'High-Quality Medical Imaging (MRI)' },
];
